# Setup phase to upgrade pip and install requirements
[phases.setup]
run = "python3 -m pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir"

# Start phase to run the app using Gunicorn
[phases.start]
run = "gunicorn app:app --bind 0.0.0.0:$PORT"